export const byer = {
    "Alta": false,
    "Hammerfest": false,
    "Honningsvåg": false,
    "Kirkenes": false,
    "Vadsø": false,
    "Vardø": false,
    "Bardufoss": false,
    "Finnsnes": false,
    "Harstad": false,
    "Tromsø": 'Tromsø', // Tromsø er false
    "Bodø": false,
    "Brønnøysund": false,
    "Fauske": false,
    "Leknes": false,
    "Mo i Rana": false,
    "Mosjøen": false,
    "Narvik": false,
    "Sandnessjøen": false,
    "Sortland": false,
    "Stokmarknes": false,
    "Svolvær": false,
    "Levanger": false,
    "Namsos": false,
    "Kolvereid": false,
    "Steinkjer": false,
    "Stjørdal": false,
    "Verdalsøra": false,
    "Trondheim": false,
    "Brekstad": false,
    "Orkanger": false,
    "Røros": false,
    "Rørvik": false,
    "Fosnavåg": false,
    "Kristiansund": false,
    "Molde": false,
    "Ulsteinvik": false,
    "Ålesund": false,
    "Åndalsnes": false,
    "Florø": false,
    "Førde": false,
    "Måløy": false,
    "Bergen": false,
    "Leirvik": false,
    "Odda": false,
    "Bryne": false,
    "Egersund": false,
    "Haugesund": false,
    "Jørpeland": false,
    "Kopervik": false,
    "Sandnes": false,
    "Sauda": false,
    "Skudeneshavn": false,
    "Stavanger": false,
    "Åkrehamn": false,
    "Flekkefjord": false,
    "Kristiansand": false,
    "Farsund": false,
    "Lyngdal": false,
    "Mandal": false,
    "Arendal": false,
    "Grimstad": false,
    "Lillesand": false,
    "Risør": false,
    "Tvedestrand": false,
    "Brevik": false,
    "Kragerø": false,
    "Langesund": false,
    "Notodden": false,
    "Porsgrunn": false,
    "Rjukan": false,
    "Skien": false,
    "Stathelle": false,
    "Holmestrand": false,
    "Horten": false,
    "Larvik": false,
    "Sandefjord": false,
    "Stavern": false,
    "Tønsberg": false,
    "Åsgårdstrand": false,
    "Drammen": false,
    "Svelvik": false,
    "Hokksund": false,
    "Hønefoss": false,
    "Kongsberg": false,
    "Drøbak": false,
    "Lillestrøm": false,
    "Sandvika": false,
    "Ski": false,
    "Jessheim": false,
    "Askim": false,
    "Fredrikstad": false,
    "Halden": false,
    "Moss": false,
    "Mysen": false,
    "Sarpsborg": false,
    "Fagernes": false,
    "Gjøvik": false,
    "Lillehammer": false,
    "Otta": false,
    "Raufoss": false,
    "Vinstra": false,
    "Elverum": false,
    "Hamar": false,
    "Kongsvinger": false,
    "Brumunddal": false,
    "Moelv": false,
    "Tynset": false,
    "Oslo": 'Oslo'
};
import tromsøimg from './public/isak-bjørgedal.jpg'
import osloimg from './public/jostlin12.jpg'
export const representantdata = {
    'Oslo':{
        img:osloimg,
        id:'054d6f37522a94beca5be20fa857792ea38181ec34593fdca204b8813707fb2a54',
        name:'Johannes Stenstad'
    },
    'Tromsø':{
        img:tromsøimg,
        id:'05501da7df5cbd52231ecd2ae48f533cbc95890493eb70dff66782da7a43296949',
        name:'Isak Bjørgedal'
    }
}